name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@main
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --no-exec --github-repo ${{ github.repository }}

  build-release:
    permissions:
      contents: write
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: linux-x86_64
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            name: linux-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            name: darwin-arm64

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          tar czvf ../../../pavo-${{ matrix.target }}.tar.gz pavo
          cd -

      - name: Publish to GitHub
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: pavo-${{ matrix.target }}.tar.gz
          file_glob: true
          overwrite: true
          tag: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: "${{ needs.create-release.outputs.body }}"

  # update-homebrew:
  #   needs: build-release
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Update Homebrew formula
  #       uses: mislav/bump-homebrew-formula-action@v3
  #       with:
  #         formula-name: pavo
  #         homebrew-tap: taiga/homebrew-tap
  #         base-branch: main
  #         download-url: https://github.com/taiga/pavo/releases/download/${{ github.ref_name }}/pavo-darwin-arm64.tar.gz
  #       env:
  #         COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
